//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL
    {
        public long ID { get; set; }
        public string P_ID { get; set; }
        public string Message { get; set; }
        public string P_OF_ID { get; set; }
        public Nullable<bool> Is_Sub { get; set; }
        public string U_CM_ID { get; set; }
        public string Sub_Done_Time { get; set; }
        public Nullable<int> CL_TYPE { get; set; }
    }
}
