//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL
    {
        public long ID { get; set; }
        public string P_ID { get; set; }
        public string P_Time { get; set; }
        public Nullable<bool> Done { get; set; }
        public string Done_Time { get; set; }
        public string F_ID { get; set; }
        public string Message { get; set; }
    }
}
